{
    "$ref": "https://www.cert.ssi.gouv.fr/openapi.json",
    "affected_systems": [
        {
            "description": "CPython versions antérieures à 3.13.0rc2",
            "product": {
                "name": "CPython",
                "vendor": {
                    "name": "Python",
                    "scada": false
                }
            }
        }
    ],
    "affected_systems_content": "",
    "content": "## Solutions\n\nSe référer au bulletin de sécurité de l'éditeur pour l'obtention des correctifs (cf. section Documentation).",
    "cves": [
        {
            "name": "CVE-2024-6232",
            "url": "https://www.cve.org/CVERecord?id=CVE-2024-6232"
        }
    ],
    "links": [],
    "reference": "CERTFR-2024-AVI-0734",
    "revisions": [
        {
            "description": "Version initiale",
            "revision_date": "2024-09-04T00:00:00.000000"
        }
    ],
    "risks": [
        {
            "description": "Déni de service"
        }
    ],
    "summary": "Une vulnérabilité a été découverte dans CPython. Elle permet à un attaquant de provoquer un déni de service.",
    "title": "Vulnérabilité dans CPython",
    "vendor_advisories": [
        {
            "published_at": "2024-09-03",
            "title": "Bulletin de sécurité Python",
            "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/"
        }
    ]
}